package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runInit scaffolds a release workspace without a full git checkout:
// .keys/ (RSA), gateway/kong.yml (auth-only routes), and optional compose/.env copies.
func runInit(dir string) error {
	if dir == "" {
		dir = "."
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(abs, "gateway"), 0o755); err != nil {
		return err
	}
	pubPEM, err := ensureKeys(abs)
	if err != nil {
		return err
	}
	kongPath := filepath.Join(abs, "gateway", "kong.yml")
	if _, err := os.Stat(kongPath); err == nil {
		fmt.Printf("keep existing %s\n", kongPath)
	} else {
		if err := os.WriteFile(kongPath, []byte(bootstrapKongYAML(pubPEM)), 0o644); err != nil {
			return err
		}
		fmt.Printf("wrote %s (auth routes only; add services with pctl sync later)\n", kongPath)
	}
	fmt.Printf("keys: %s\n", filepath.Join(abs, ".keys"))
	fmt.Println("next: download deploy/compose.release.yml → compose.yml, set .env, then:")
	fmt.Println("  docker compose --profile bundled-db up -d")
	return nil
}

func bootstrapKongYAML(pubPEM string) string {
	var b strings.Builder
	b.WriteString("_format_version: \"3.0\"\n\n")
	b.WriteString("# Generated by pctl init — auth entry only. Replace via pctl sync when you add services.\n")
	b.WriteString("services:\n")
	b.WriteString("  - name: auth\n    url: http://auth:8080\n    retries: 2\n    routes:\n")
	b.WriteString("      - name: auth-route\n        paths: [\"/auth\"]\n        strip_path: false\n")
	b.WriteString("        plugins:\n          - name: rate-limiting\n")
	b.WriteString("            config: { minute: 60, policy: redis, redis: { host: redis, port: 6379, timeout: 2000 }, limit_by: ip }\n")
	b.WriteString("      - name: platform-root\n        paths: [\"/\"]\n        strip_path: false\n\n")
	b.WriteString("consumers:\n  - username: pf-auth-issuer\n    jwt_secrets:\n")
	b.WriteString("      - key: pf-auth\n        algorithm: RS256\n        rsa_public_key: |\n")
	for _, line := range strings.Split(strings.TrimRight(pubPEM, "\n"), "\n") {
		b.WriteString("          " + line + "\n")
	}
	return b.String()
}
