package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const generatedHeader = "# ⚠️ GENERATED BY pctl sync — 手改无效，改 services/*/{service,plugin}.yaml 后重新 sync\n"

// runSync 由清单生成 gateway/kong.yml 与 docker-compose.services.yml（含 gateway/plugin-pg/网络）。
func runSync(root string) error {
	manifests, err := loadManifests(root)
	if err != nil {
		return err
	}
	if err := validateManifests(manifests); err != nil {
		return err
	}
	pubPEM, err := ensureKeys(root)
	if err != nil {
		return err
	}

	var enabled []Manifest
	for _, m := range manifests {
		if m.IsEnabled() {
			enabled = append(enabled, m)
		} else {
			fmt.Printf("  %s: disabled，跳过\n", m.ID)
		}
	}

	if v := envFromRoot(root, "PF_REDIS_URL"); v != "" {
		os.Setenv("PF_REDIS_URL", v)
	} else {
		os.Setenv("PF_REDIS_URL", "redis://redis:6379/0")
	}
	kong := renderKong(enabled, pubPEM, redisRateLimit())
	if err := os.WriteFile(filepath.Join(root, "gateway", "kong.yml"), []byte(kong), 0o644); err != nil {
		return fmt.Errorf("write kong.yml: %w", err)
	}
	compose := renderServicesCompose(enabled)
	if err := os.WriteFile(filepath.Join(root, "docker-compose.services.yml"), []byte(compose), 0o644); err != nil {
		return fmt.Errorf("write docker-compose.services.yml: %w", err)
	}
	if err := writeEgressConfs(root, enabled); err != nil {
		return err
	}
	fmt.Printf("sync 完成：%d 个服务（enabled）→ kong.yml + docker-compose.services.yml\n", len(enabled))
	return nil
}

// writeEgressConfs 为声明 permissions.egress 的第三方插件生成 squid 域名白名单配置
// （specs/024，附录 H 降级③兑现）：插件网络仍 internal 全断外网，出网只能走 egress sidecar。
func writeEgressConfs(root string, manifests []Manifest) error {
	for _, m := range manifests {
		if !m.IsThirdParty() || len(m.Permissions.Egress) == 0 {
			continue
		}
		var b strings.Builder
		b.WriteString("# ⚠️ GENERATED BY pctl sync — 手改无效，改 services/" + m.ID + "/plugin.yaml 的 permissions.egress\n")
		b.WriteString("http_port 3128\n")
		b.WriteString("acl SSL_ports port 443\n")
		b.WriteString("acl Safe_ports port 80 443\n")
		b.WriteString("acl CONNECT method CONNECT\n")
		b.WriteString("http_access deny !Safe_ports\n")
		b.WriteString("http_access deny CONNECT !SSL_ports\n")
		// squid 不允许重叠条目（'.x.com' 已含 'x.com'）：出现带点通配时丢弃裸域名
		dotted := map[string]bool{}
		for _, d := range m.Permissions.Egress {
			if strings.HasPrefix(d, ".") {
				dotted[strings.TrimPrefix(d, ".")] = true
			}
		}
		seen := map[string]bool{}
		for _, d := range m.Permissions.Egress {
			if !strings.HasPrefix(d, ".") && dotted[d] {
				continue
			}
			if seen[d] {
				continue
			}
			seen[d] = true
			b.WriteString("acl allowed dstdomain " + d + "\n")
		}
		b.WriteString("http_access allow allowed\nhttp_access deny all\n")
		path := filepath.Join(root, "gateway", "egress-"+m.ID+".conf")
		if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// ensureKeys 保证 RS256 密钥对存在（与 auth 的生成逻辑幂等互备），返回公钥 PEM。
func ensureKeys(root string) (string, error) {
	privPath := filepath.Join(root, ".keys", "pf-auth.pem")
	pubPath := privPath + ".pub"
	if raw, err := os.ReadFile(pubPath); err == nil {
		return string(raw), nil
	}
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(privPath), 0o755); err != nil {
		return "", err
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	if err := os.WriteFile(privPath, privPEM, 0o600); err != nil {
		return "", err
	}
	pubDER, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	if err != nil {
		return "", err
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	if err := os.WriteFile(pubPath, pubPEM, 0o644); err != nil {
		return "", err
	}
	fmt.Println("已生成 RS256 密钥对 → .keys/（gitignore；生产环境用密钥管理分发）")
	return string(pubPEM), nil
}

func readEnvVar(path, key string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if ok && strings.TrimSpace(k) == key {
			return strings.Trim(strings.TrimSpace(v), `"'`), nil
		}
	}
	return "", fmt.Errorf("%s not in %s", key, path)
}

func envFromRoot(root, key string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	v, err := readEnvVar(filepath.Join(root, ".env"), key)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(v)
}

func redisRateLimit() bool {
	v := strings.TrimSpace(os.Getenv("PF_REDIS_URL"))
	return v != "" && v != "0" && strings.ToLower(v) != "false"
}

func rateLimitYAML(minute int, indent string) string {
	if redisRateLimit() {
		conn, err := parseRedisURL(os.Getenv("PF_REDIS_URL"))
		if err != nil {
			conn = redisConn{Host: "redis", Port: 6379}
		}
		return fmt.Sprintf("%s- name: rate-limiting\n%s  config: { minute: %d, policy: redis, %s, limit_by: ip }\n",
			indent, indent, minute, kongRedisInline(conn))
	}
	return fmt.Sprintf("%s- name: rate-limiting\n%s  config: { minute: %d, policy: local, limit_by: ip }\n", indent, indent, minute)
}

// openScopeGateYAML 生成开放路由的 scope 校验 pre-function（specs/009）：
// 要求 tokenType=app 且路由 scope ∈ token.scopes，否则 403；并写 X-PF-App-Key 供限流/计量。
func openScopeGateYAML(scope, indent string) string {
	// Kong 沙箱禁止 require(jwt_parser)，故手动解 JWT payload（不验签——签名由 jwt 插件校验）。
	lua := strings.ReplaceAll(`local auth = kong.request.get_header("authorization")
if not auth then return kong.response.exit(401, { error = "app token required" }) end
local token = string.gsub(auth, "^Bearer%s+", "")
local seg = {}
for s in string.gmatch(token, "[^.]+") do seg[#seg+1] = s end
if #seg < 2 then return kong.response.exit(401, { error = "invalid token" }) end
local b64 = seg[2]:gsub("-", "+"):gsub("_", "/")
local pad = #b64 % 4
if pad > 0 then b64 = b64 .. string.rep("=", 4 - pad) end
local raw = ngx.decode_base64(b64)
if not raw then return kong.response.exit(401, { error = "invalid token" }) end
local ok_json, claims = pcall(function() return require("cjson").decode(raw) end)
if not ok_json or not claims then return kong.response.exit(401, { error = "invalid token" }) end
if claims.tokenType ~= "app" then return kong.response.exit(403, { error = "open API requires an app token" }) end
local ok = false
for _, s in ipairs(claims.scopes or {}) do if s == "__SCOPE__" then ok = true break end end
if not ok then return kong.response.exit(403, { error = "missing scope __SCOPE__" }) end
kong.service.request.set_header("X-PF-App-Key", claims.appKey or "")`, "__SCOPE__", scope)

	var b strings.Builder
	b.WriteString(indent + "- name: pre-function\n")
	b.WriteString(indent + "  config:\n")
	b.WriteString(indent + "    access:\n")
	b.WriteString(indent + "      - |\n")
	for _, line := range strings.Split(lua, "\n") {
		b.WriteString(indent + "          " + line + "\n")
	}
	return b.String()
}

// serviceCallGateYAML 网关级 calls 放行（specs/025，附录 H 降级①兑现）：
// service token 访问服务 X 必须携带 "X" 或 "X:*" 前缀 scope（scope 来源 = 清单 permissions.calls，
// auth 按 calls 签发）。用户 access token / app token 不受影响。
// ⚠️ Kong 同名插件按"最具体实例"生效：路由级 pre-function 会覆盖全局 SSO cookie 映射，
// 故此 Lua 必须内含 cookie→Bearer 逻辑（specs/006 的超集）。
func serviceCallGateYAML(svcID, indent string) string {
	lua := strings.ReplaceAll(`local auth = kong.request.get_header("authorization")
if not auth then
  local ck = kong.request.get_header("cookie")
  if ck then
    local t = string.match(ck, "pf_access=([^;%s]+)")
    if t then auth = "Bearer " .. t; kong.service.request.set_header("authorization", auth) end
  end
end
if auth then
  local token = string.gsub(auth, "^Bearer%s+", "")
  local seg = {}
  for s in string.gmatch(token, "[^.]+") do seg[#seg+1] = s end
  if #seg >= 2 then
    local b64 = seg[2]:gsub("-", "+"):gsub("_", "/")
    local pad = #b64 % 4
    if pad > 0 then b64 = b64 .. string.rep("=", 4 - pad) end
    local raw = ngx.decode_base64(b64)
    if raw then
      local ok_json, claims = pcall(function() return require("cjson").decode(raw) end)
      if ok_json and claims and claims.tokenType == "service" then
        local allowed = false
        for _, s in ipairs(claims.scopes or {}) do
          if s == "__SVC__" or string.sub(s, 1, string.len("__SVC__:")) == "__SVC__:" then allowed = true break end
        end
        if not allowed then
          return kong.response.exit(403, { error = "service token lacks a __SVC__ scope (declare it in permissions.calls)" })
        end
      end
    end
  end
end`, "__SVC__", svcID)

	var b strings.Builder
	b.WriteString(indent + "- name: pre-function\n")
	b.WriteString(indent + "  config:\n")
	b.WriteString(indent + "    access:\n")
	b.WriteString(indent + "      - |\n")
	for _, line := range strings.Split(lua, "\n") {
		b.WriteString(indent + "          " + line + "\n")
	}
	return b.String()
}

// rateLimitByAppYAML 按 app 限流（X-PF-App-Key）。redis 可用则集中计数。
func rateLimitByAppYAML(minute int, indent string) string {
	if redisRateLimit() {
		conn, err := parseRedisURL(os.Getenv("PF_REDIS_URL"))
		if err != nil {
			conn = redisConn{Host: "redis", Port: 6379}
		}
		return fmt.Sprintf("%s- name: rate-limiting\n%s  config: { minute: %d, policy: redis, %s, limit_by: header, header_name: X-PF-App-Key }\n",
			indent, indent, minute, kongRedisInline(conn))
	}
	return fmt.Sprintf("%s- name: rate-limiting\n%s  config: { minute: %d, policy: local, limit_by: header, header_name: X-PF-App-Key }\n", indent, indent, minute)
}

func renderKong(manifests []Manifest, pubPEM string, _ bool) string {
	var b strings.Builder
	b.WriteString("_format_version: \"3.0\"\n\n")
	b.WriteString(generatedHeader)
	b.WriteString("services:\n")
	b.WriteString("  - name: auth\n    url: http://auth:8080\n    retries: 2\n    routes:\n")
	b.WriteString("      - name: auth-route\n        paths: [\"/auth\"]\n        strip_path: false\n        plugins:\n")
	b.WriteString(rateLimitYAML(60, "          "))
	b.WriteString("      - name: platform-root\n        paths: [\"/\"]\n        strip_path: false\n")
	// SSO 统一管理壳：console 经网关同源挂载（specs/006）
	b.WriteString("  - name: console\n    url: http://console:8080\n    retries: 2\n    routes:\n")
	b.WriteString("      - name: platform-console\n        paths: [\"/platform/console\"]\n        strip_path: true\n")
	// pf-ui 组件库（specs/028）：公开静态资产，全部 console/账号页同源引用
	b.WriteString("      - name: platform-ui\n        paths: [\"/platform/ui\"]\n        strip_path: false\n")
	for _, m := range manifests {
		fmt.Fprintf(&b, "\n  - name: %s\n    url: http://%s:%d\n    retries: 2\n    routes:\n", m.ID, m.ID, m.Runtime.Port)
		for i, p := range publicPrefixes(m) {
			fmt.Fprintf(&b, "      - name: %s-public-%d\n        paths: [\"%s\"]\n        strip_path: %v\n", m.ID, i, p, m.Mount.StripPath)
		}
		// 开放平台路由（specs/009）：更具体的路径 + 方法，优先于 -protected 命中
		for i, o := range m.OpenAPI {
			fmt.Fprintf(&b, "      - name: %s-open-%d\n        paths: [\"%s\"]\n        methods: [\"%s\"]\n        strip_path: %v\n",
				m.ID, i, o.Path(), o.Method(), m.Mount.StripPath)
			b.WriteString("        plugins:\n")
			b.WriteString("          - name: jwt\n            config: { key_claim_name: iss, claims_to_verify: [\"exp\"] }\n")
			b.WriteString(openScopeGateYAML(o.Scope, "          "))
			b.WriteString(rateLimitByAppYAML(60, "          "))
		}
		fmt.Fprintf(&b, "      - name: %s-protected\n        paths: [\"%s\"]\n        strip_path: %v\n", m.ID, m.Mount.Path, m.Mount.StripPath)
		if m.Auth.Required || m.Limits.RatePerMinute > 0 {
			b.WriteString("        plugins:\n")
		}
		if m.Auth.Required {
			b.WriteString("          - name: jwt\n            config: { key_claim_name: iss, claims_to_verify: [\"exp\"] }\n")
			b.WriteString(serviceCallGateYAML(m.ID, "          ")) // 网关级 calls 放行（specs/025）
		}
		if m.Limits.RatePerMinute > 0 {
			b.WriteString(rateLimitYAML(m.Limits.RatePerMinute, "          "))
		}
	}
	// SSO：全局 pre-function，无 Authorization 但有 pf_access Cookie 时补 Bearer（specs/006）
	b.WriteString(`
# 全局 pre-function：cookie pf_access → Authorization: Bearer（SSO，specs/006）
plugins:
  - name: pre-function
    config:
      access:
        - |
          local h = kong.request.get_header("authorization")
          if not h then
            local ck = kong.request.get_header("cookie")
            if ck then
              local t = string.match(ck, "pf_access=([^;%s]+)")
              if t then kong.service.request.set_header("authorization", "Bearer " .. t) end
            end
          end
  # 计量（specs/013）：结构化 JSON 访问日志到 stdout，含 app key / request id / route / status
  # 由 promtail 采集进 Loki。log serializer 自带 request.headers，promtail 侧提取 X-PF-App-Key。
  - name: file-log
    config:
      path: /dev/stdout
      custom_fields_by_lua:
        pf_app_key: "return kong.request.get_header('x-pf-app-key') or ''"
        pf_request_id: "return kong.request.get_header('x-request-id') or kong.ctx.shared.request_id or ''"

# jwt 插件按 iss=pf-auth 匹配此 consumer，RS256 公钥验签（私钥仅 auth 持有）
consumers:
  - username: pf-auth-issuer
    jwt_secrets:
      - key: pf-auth
        algorithm: RS256
        rsa_public_key: |
`)
	for _, line := range strings.Split(strings.TrimRight(pubPEM, "\n"), "\n") {
		b.WriteString("          " + line + "\n")
	}
	return b.String()
}
